version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/StorageLibrary"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/src"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "[docker] " (no colon, but a trailing whitespace)
      prefix: "[docker] "

  - package-ecosystem: 'npm' 
    directory: '/' 
    schedule: 
      interval: 'daily' 
    open-pull-requests-limit: 0
