apiVersion: v1
kind: Service
metadata:
  labels:
    app: azurestorageexplorer
  name: azurestorageexplorer
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: azurestorageexplorer
  sessionAffinity: None
  type: ClusterIP
