apiVersion: v1
kind: Service
metadata:
  name: {{ include "azurestorageexplorer.fullname" . }}
  labels:
    {{- include "azurestorageexplorer.labels" . | nindent 4 }}
  {{- if .Values.serviceMetrics.enabled }}
  annotations:
    {{- range .Values.serviceMetrics.annotations }}
    {{.}}
    {{- end}}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "azurestorageexplorer.selectorLabels" . | nindent 4 }}
