//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageManager {
    
    
    public partial class _Default {
        
        /// <summary>
        /// UC_Containers1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::StorageManager.Controls.UC_Containers UC_Containers1;
        
        /// <summary>
        /// UC_Tables1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::StorageManager.Controls.UC_Tables UC_Tables1;
        
        /// <summary>
        /// UC_Queues1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::StorageManager.Controls.UC_Queues UC_Queues1;
        
        /// <summary>
        /// UC_Blob1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::StorageManager.Controls.UC_Blob UC_Blob1;
        
        /// <summary>
        /// UC_Entities1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::StorageManager.Controls.UC_Entities UC_Entities1;
        
        /// <summary>
        /// UC_Messages1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::StorageManager.Controls.UC_Messages UC_Messages1;
    }
}
