<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>skyfs</AssemblyName>
    <RootNamespace>SkyFs</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.1.0</Version>
    <Authors>Sebastián Gómez</Authors>
    <RepositoryUrl>https://github.com/sebagomez/azurestorageexplorer</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\StorageLibrary\StorageLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SkyFsTests" />
  </ItemGroup>

</Project>
