name: Docker build

on:
  push:
    branches:
      - master
    paths:
    - build-image/*
    - src/**
    - .github/workflows/docker-build.yml

env:
  config: Release
  docker_user: sebagomez
  repository: azurestorageexplorer

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install XMLLint
      run: | 
        sudo apt-get update
        sudo apt-get install libxml2-utils
    - name: Get tagname
      run: echo "build_number=$(./version.sh)" >> $GITHUB_ENV
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.docker_user }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        tags: ${{ env.docker_user }}/${{ env.repository }}:latest,${{ env.docker_user }}/${{ env.repository }}:${{ env.build_number }}
        build-args: BUILD=${{ env.build_number }}
        context: ./src
        push: true 
