name: .NET build

on:
  push:
    paths:
    - src/**
    - tests/**
    - .github/workflows/dotnet-build.yml
  pull_request:
    paths:
    - src/**
    - tests/**
    - .github/workflows/dotnet-build.yml

env:
  config: Release

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x'
    - name: Local Web Build
      run: dotnet build --configuration $config ./src/web/web.csproj
    - name: Local Cli Build
      run: dotnet build --configuration $config ./src/cli/cli.csproj
    - name: Run Tests
      run:  | 
        dotnet test ./tests/StorageLibTests/StorageLibTests.csproj
        dotnet test ./tests/SkyFsTests/SkyFsTests.csproj
