name: .NET build

on:
  push:
    paths:
    - src/**
    - tests/**
    - .github/workflows/dotnet-build.yml
  pull_request:
    paths:
    - src/**
    - tests/**
    - .github/workflows/dotnet-build.yml

env:
  config: Release

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Local Build
      run: dotnet build --configuration $config ./src/web/web.csproj
    - name: Run Tests
      run: dotnet test ./tests/StorageLibTests/StorageLibTests.csproj
