name: Helm release

on:
  push:
    branches:
      - main
    paths:
    - helm/**/*
    - src/web/Directory.Build.props
    - .github/workflows/helm-release.yml

env:
  config: Release

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install XMLLint
      run: |
        sudo apt-get update
        sudo apt-get install libxml2-utils

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.10.0

    - name: Get tagname
      run: |
        build_number=$(./utils/version.sh)
        echo $build_number
        app_number=$(sed 's/\.//g' <<< $build_number)
        echo $app_number
        sed -i -E "s/appVersion:.*/appVersion: \"$build_number\"/" ./helm/azurestorageexplorer/Chart.yaml
        sed -i -E "s/REPLACE_APP_VERSION/$app_number/" ./helm/azurestorageexplorer/Chart.yaml 
        sed -i -E "s/  tag:.*/  tag: \"$build_number\"/" ./helm/azurestorageexplorer/values.yaml

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      with:
        charts_dir: helm
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"